language: c++
compiler:
 - gcc
 - clang
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Debug -DACADO_WITH_TESTING=ON ..
 - make
after_success:
 - make test
notifications:
  recipients:
    - builds@acadotoolkit.org
  email:
    on_failure: always
