language: c++
compiler:
 - gcc
 - clang
env:
 global:
   - secure: "XVZ3qVCwiqySzDWl9prD1+CtNZDod8IWiBEdPGrRpJmcj+RUuBGqkveiTmOKOKKpSf2cJ+8ulconMcntrAQe98I0UE8g7pytkdITr0iSJL4uK/kLQY1aoP+Yy/6tgwFbbj66rvPBeAZl6nWoSEN+r/zNL9O6KGrE+JvYFEWoteQ="
   - secure: "naQwKgv0Huuna+Jrs6WJdTHvyYv2TGsQlzgL0kUuFEibMNY/AcAJceWHXDSZx13oIvZLRgjixmvNuJYlcVVV4K9KmAYvUhggQobHhLgS50x1xe80c4TIvn6Zf12vK3H+byGwfF1KQVIN1i0O1JF/ltK9/PBCit1dfaRgu/nFdRM="
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Debug -DACADO_WITH_TESTING=ON ..
 - make
after_success:
 # Run the tests, allowed to fail
 - make test
 # Deploy the source code
 - cd ..
 - "./misc/deploy_code.sh"
notifications:
  recipients:
    - builds@acadotoolkit.org
  email:
    on_failure: always
