language: c++
compiler:
 - gcc
 - clang
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_ACADO_TESTING=ON..
 - make
after_success:
 - make test
notifications:
  recipients:
    - mvukov@gmail.com
  email:
    on_failure: always
