language: c++
compiler:
 - gcc
 - clang
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Debug ..
 - make
notifications:
  recipients:
    - mvukov@gmail.com
  email:
    on_failure: always
